model_config:
  model: UNet1 #the directory to which the results are saved
  initial_filter_size: [64]
  kernel: [3]
  drop_out_rate: [0.2]
  input_size: [240, 240]    #[1536, 1536] #h, w 
  channel: 1
  num_class: 4
  model_type: 'TransUnet' #multi_task, attention, fourier1, fourier1_2, single, TransUnet
  dropout: False
  anydepth: False
train_config:
  loss: dice_bce_mc
  accuracy: dice_bce_mc
  optimizer: SGD #SGD
  lr_rate: [0.01]
  weight_decay: [0.0001]
  batch_size: [1]
  epochs: 10
  early_stop: 20
  num_workers: 20
  seed: [7,35]
  use_cuda: True
dataset_config:
  train_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/val/']
  val_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/val/']
  test_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/val/']
  augmentation: False
  save_dir: onurdeneme
  class_names: ['background','liver']
resume:
  flag: False
  path: hd_exp1_123_bs/models/last_epoch.pt
  epoch: 75

